### ISSUE TITLE
Where's The PML Ref Man?

### ISSUE THREAD

**Issue by tajmone** [pml-lang/user-manual#10]
I wanted to fix some typos and broken styles in the _PML Reference Manual_, but can't locate its source neither in this repository nor in the converter repository.

Where are the Ref Man sources stored?

I can see the Ref Man resources in pml-lang/converter, but not the PML source docs. Are they embedded in the PPL code?

It might be worth mentioning it in the README of this project.

**Comment by pml-lang** [comment]
The reference manual is created automatically by the converter's `create_reference_manual` command. The PML source code is saved in a temporary directory (parameter `temp_directory`). The text is extracted from the converter's PPL sources (for example in [se_PML_image_formal_node.ppl](https://github.com/pml-lang/converter/blob/main/work/src/PPL/dev/pml/converter/data/formal_node/block/without_child_nodes/media/se_PML_image_formal_node.ppl)).

I will create a repository with the PML source code of the reference manual. That will make it easier for people to submit fixes via PRs, and discuss enhancements.

**Comment by celtic-coder** [comment]
A good idea! There's a few suggestions I would like to make concerning the reference manual.

**Comment by pml-lang** [comment]
I've created a [repository](https://github.com/pml-lang/reference-manual) with the PML source code of the PML reference manual.

Now everybody can submit PRs 😀
