### ISSUE TITLE
Creating local HTML version fails: no "examples" folder

### ISSUE THREAD

**Issue by celtic-coder** [pml-lang/user-manual#5]
Hi Christian (@pml-lang),

### Error:

Running the `pmlc convert --input_file input/text/index.pml` command to generate a local HTML version of the User Manual fails:

![pmlc-error](https://user-images.githubusercontent.com/11787866/114286653-9efb4900-9a58-11eb-8379-4a58d988f50f.png)

Error (on Windows):

`\input\examples\simple_document\03_01_document_example.pml doesn't exist.`

### Workaround:

Commenting out lines 15 and 16 in the `05_anatomy.pml` resolves the issue:

https://github.com/pml-lang/user-manual/blob/241dd63aaad257ad9a0ed59029f78ef38baed136/input/text/05_anatomy.pml#L15-L16

### Core Problem:

The problem is that the "constant" definition for `examples_dir` in the `index.pml` file is invalid as there is no "input/examples" folder in the repo:

https://github.com/pml-lang/user-manual/blob/241dd63aaad257ad9a0ed59029f78ef38baed136/input/text/index.pml#L5

### Possible Solution?

Should an error be raised for a "constant" value that refers to either a file or folder if they do not actually exist?

Kind Regards,
Liam

**Comment by pml-lang** [comment]
Hi Liam,

Thanks for this very-well-described bug report and your previous comments. Welcome on board!

The bug is now fixed.

The culprit was the following superflous line in `.gitignore`:
```
**/examples
```
The line has been removed, so that there is now an `input/examples` folder in the repo.

> Should an error be raised for a "constant" value that refers to either a file or folder if they do not actually exist?

That would be really nice, but it's currently not possible. Reason:
All constants are simply untyped strings. Hence the converter doesn't know which type of value is supposed to be contained in a constant, and can't therefore do any checks.
In a future version we might add typed/checked constants, so that instead of:
```
[const examples_dir=input/examples]
```
... we can write something like:
```
[const existing_directory examples_dir=input/examples]
```

**Comment by celtic-coder** [comment]
Hi Christian (@pml-lang),

Thank you for the welcome! I have been using AsciiDoctor for the past six years and am intrigued by this new markup language. I stumbled on your repo when I saw Tristano Ajmone's  [Sublime Text 3 syntax for PML (Practical Markup Language)](https://github.com/tajmone/Sublime-PML) repo.

Before AsciiDoctor, I briefly used reStructuredText and, for a long time, used [Txt2Tags](https://github.com/txt2tags/txt2tags) as it was a kind of "Pandoc" for markup output. Txt2Tags started in 2001, and I was probably using it soon after it became available. The [markup](https://txt2tags.org/markup.html) was simple and the output could be post-processed, both useful features.

It is difficult for a markup language to be "all things to all men", as it is hard to keep everyone happy, but from what I have seen so far, PML has a well-rounded set of features. It will be interesting to observe how it develops going forward.

Kind Regards,
Liam

**Comment by pml-lang** [comment]
Thank you Liam, for your kind words.

And thanks for the link to Txt2Tags, which I didn't know.

You and Tristano have a long and very extensive experience with markup languages. Your advice and any kind of feedback is very useful and helps to steadily improve PML.

I am currently working on a new parser for PML. Parsing will be very fast, and some existing nodes (e.g. `const` and `insert` nodes) will be more powerful. After that I will add new features, based on suggestions from the community, as well as my own TODO list. If you need anything for your own use cases then please let me know.
